# -*- coding: utf-8 -*-
"""birthday_wish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13z_3LpV1w3DQLuTvxQOdej-E7EThZU7S
"""

import streamlit as st
from PIL import Image, ImageDraw, ImageFont
import io
from datetime import datetime

# -------------------
# PAGE CONFIG
# -------------------
st.set_page_config(
    page_title="Birthday Magic",
    page_icon="🎂",
    layout="wide"
)

# -------------------
# CSS
# -------------------
st.markdown("""
<style>

.stApp{
background: linear-gradient(135deg,#0f172a,#1e293b);
color:white;
}

.main-title{
text-align:center;
font-size:55px;
font-weight:bold;
background:linear-gradient(to right,#fbbf24,#ec4899);
-webkit-background-clip:text;
-webkit-text-fill-color:transparent;
}

.glass{
background:rgba(255,255,255,0.1);
padding:20px;
border-radius:20px;
backdrop-filter: blur(10px);
border:1px solid rgba(255,255,255,0.2);
}

.card{
background:white;
padding:20px;
border-radius:20px;
color:black;
}

</style>
""", unsafe_allow_html=True)

# -------------------
# TITLE
# -------------------
st.markdown(
    '<h1 class="main-title">🎂 Birthday Magic App 🎉</h1>',
    unsafe_allow_html=True
)

st.write("")

# -------------------
# INPUT SECTION
# -------------------
col1, col2 = st.columns([1,1])

with col1:

    st.markdown('<div class="glass">', unsafe_allow_html=True)

    uploaded_photo = st.file_uploader(
        "📸 Upload Photo",
        type=["png","jpg","jpeg"]
    )

    name = st.text_input(
        "👤 Name"
    )

    age = st.number_input(
        "🎂 Age",
        min_value=1,
        max_value=120,
        value=18
    )

    relation = st.selectbox(
        "💝 Relationship",
        [
            "Friend",
            "Best Friend",
            "Brother",
            "Sister",
            "Mother",
            "Father",
            "Boyfriend",
            "Girlfriend",
            "Teacher",
            "Colleague"
        ]
    )

    theme = st.selectbox(
        "🎨 Theme",
        [
            "Royal",
            "Cute",
            "Elegant",
            "Funny"
        ]
    )

    language = st.selectbox(
        "🌍 Language",
        [
            "English",
            "Hindi",
            "Gujarati"
        ]
    )

    music = st.file_uploader(
        "🎵 Upload Birthday Music",
        type=["mp3","wav"]
    )

    st.markdown('</div>', unsafe_allow_html=True)

# -------------------
# THEME COLORS
# -------------------
theme_colors = {
    "Royal":"#fbbf24",
    "Cute":"#ec4899",
    "Elegant":"#6366f1",
    "Funny":"#f97316"
}

accent = theme_colors[theme]

# -------------------
# WISH GENERATOR
# -------------------
def generate_wish(name, age, relation, language):

    if language == "English":
        return f"""
🎂 Happy Birthday {name}! 🎂

May your {age}th year bring happiness,
success, love and unforgettable memories.

You are an amazing {relation}
and deserve the very best.

Enjoy your special day! 🎉
"""

    elif language == "Hindi":

        return f"""
🎂 जन्मदिन मुबारक हो {name}! 🎂

आपका यह {age}वाँ वर्ष
खुशियों, सफलता और प्रेम से भरा रहे।

आप एक शानदार {relation} हैं।

आपका दिन बहुत खूबसूरत हो। 🎉
"""

    else:

        return f"""
🎂 જન્મદિવસની હાર્દિક શુભેચ્છાઓ {name}! 🎂

તમારું {age}મું વર્ષ
ખુશી, સફળતા અને પ્રેમથી ભરેલું રહે.

તમે એક અદ્ભુત {relation} છો.

તમારો દિવસ ખૂબ જ સુંદર રહે. 🎉
"""

# -------------------
# GENERATE
# -------------------
with col2:

    if st.button("🎉 Generate Birthday Card"):

        st.balloons()

        for i in range(3):
            st.snow()

        wish = generate_wish(
            name,
            age,
            relation,
            language
        )

        st.markdown(
            f"""
            <div class="card">
            <h2 style="color:{accent};">
            🎊 Birthday Wish
            </h2>
            <pre style="font-size:18px;">
{wish}
            </pre>
            </div>
            """,
            unsafe_allow_html=True
        )

        if uploaded_photo:
            image = Image.open(uploaded_photo)

            st.image(
                image,
                caption="Birthday Star 🌟",
                use_container_width=True
            )

        if music:
            st.audio(music)

        # -------------------
        # CREATE STORY CARD
        # -------------------

        width = 1080
        height = 1920

        card = Image.new(
            "RGB",
            (width,height),
            accent
        )

        draw = ImageDraw.Draw(card)

        try:
            title_font = ImageFont.truetype(
                "arial.ttf",
                80
            )
            body_font = ImageFont.truetype(
                "arial.ttf",
                45
            )
        except:
            title_font = ImageFont.load_default()
            body_font = ImageFont.load_default()

        draw.text(
            (120,150),
            "🎂 HAPPY BIRTHDAY 🎂",
            fill="white",
            font=title_font
        )

        draw.text(
            (100,450),
            wish,
            fill="white",
            font=body_font
        )

        if uploaded_photo:

            image = Image.open(uploaded_photo)

            image = image.resize(
                (500,500)
            )

            card.paste(
                image,
                (290,1200)
            )

        img_bytes = io.BytesIO()

        card.save(
            img_bytes,
            format="PNG"
        )

        img_bytes.seek(0)

        st.image(
            card,
            caption="📱 Instagram Story Card",
            use_container_width=True
        )

        st.download_button(
            label="📥 Download Birthday Card",
            data=img_bytes,
            file_name=f"{name}_birthday_card.png",
            mime="image/png"
        )

# -------------------
# FOOTER
# -------------------
st.markdown("---")

st.markdown(
f"""
<center>
<h4 style='color:lightgray;'>
Made with ❤️ | {datetime.now().year}
</h4>
</center>
""",
unsafe_allow_html=True
)