# -*- coding: utf-8 -*-
"""ML project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nG7TiPcjLptGuj0E0TZ47V2jzshPKs03
"""

from google.colab import files
uploaded = files.upload()

data = pd.read_csv("Disease_Prediction_Symptoms_1000.csv")
data

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

import joblib

import streamlit as st

st.set_page_config(page_title="Disease Prediction System")
st.title("Disease Prediction Based on Symptoms")
st.write("Enter symptoms to predict the most likely disease.")

!streamlit run app.py &>/content/logs.txt &

def load_data():
  df = pd.read_csv("Disease_Prediction_Symptoms_1000.csv")
  return df

data = load_data()
data

encoder = LabelEncoder()
data['Disease'] = encoder.fit_transform(data['Disease'])
data

x = data.drop('Disease', axis=1)
y = data['Disease']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

model = RandomForestClassifier(n_estimators=700,max_depth=8)
model.fit(x_train, y_train)

accuracy = model.score(x_test, y_test)
print("Accuracy: ", accuracy)

st.subheader("Select Symptoms (Yes / No)")

def user_input():
    fever = st.checkbox("Fever")
    cough = st.checkbox("Cough")
    fatigue = st.checkbox("Fatigue")
    headache = st.checkbox("Headache")
    nausea = st.checkbox("Nausea")
    chest_pain = st.checkbox("Chest Pain")
    thirst = st.checkbox("Excessive Thirst")
    weight_loss = st.checkbox("Weight Loss")
    frequent_urination = st.checkbox("Frequent Urination")

    return [[
        fever, cough, fatigue, headache, nausea,
        chest_pain, thirst, weight_loss, frequent_urination
    ]]

input_data = user_input()

encoder = LabelEncoder()
if st.button("Predict Disease"):
    prediction = model.predict(input_data)
    disease_name = encoder.inverse_transform(prediction)[0]

    st.success(f"Predicted Disease: **{disease_name}**")

st.subheader("Model Performance")
st.write(f"Accuracy: **{accuracy * 100:.2f}%**")

joblib.dump(model, "project.pkl")

