# -*- coding: utf-8 -*-
"""ST code for project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQTnITHX5lLrzbR2-DItijIKw6Z3MprZ
"""

import pickle

st.set_page_config(page_title="Disease Prediction System")
st.title("Disease Prediction Based on Symptoms")
st.write("Enter symptoms to predict the most likely disease.")

model = pickle.load(open("model.pkl", "rb"))
encoder = pickle.load(open("encoder.pkl", "rb"))

st.subheader("Select Symptoms (Yes / No)")

def user_input():
    fever = st.checkbox("Fever")
    cough = st.checkbox("Cough")
    fatigue = st.checkbox("Fatigue")
    headache = st.checkbox("Headache")
    nausea = st.checkbox("Nausea")
    chest_pain = st.checkbox("Chest Pain")
    thirst = st.checkbox("Excessive Thirst")
    weight_loss = st.checkbox("Weight Loss")
    frequent_urination = st.checkbox("Frequent Urination")

    return [[
        fever, cough, fatigue, headache, nausea,
        chest_pain, thirst, weight_loss, frequent_urination
    ]]

encoder = LabelEncoder()
if st.button("Predict Disease"):
    prediction = model.predict(input_data)
    disease_name = encoder.inverse_transform(prediction)[0]

    st.success(f"Predicted Disease: **{disease_name}**")

st.subheader("Model Performance")
st.write(f"Accuracy: **{accuracy * 100:.2f}%**")