# -*- coding: utf-8 -*-
"""ST code for project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQTnITHX5lLrzbR2-DItijIKw6Z3MprZ
"""

#!pip install streamlit
import streamlit as st
import pickle
import os

st.title("🩺 Disease Prediction System")

if not os.path.exists("disease_model.pkl"):
    st.error("Model file not found!")
    st.stop()

if not os.path.exists("label_encoder.pkl"):
    st.error("Encoder file not found!")
    st.stop()

model = pickle.load(open("disease_model.pkl", "rb"))
le = pickle.load(open("label_encoder.pkl", "rb"))


# model UI


import pickle

st.title("🩺 Disease Prediction System")


st.subheader("Select Symptoms")

symptoms = [
    "Fever","Cough","Fatigue","Headache","Nausea",
    "Chest_Pain","Thirst","Weight_Loss","Frequent_Urination"
]

user_input = []
for s in symptoms:
    user_input.append(int(st.checkbox(s)))

if st.button("Predict"):
    prediction = model.predict([user_input])
    disease = le.inverse_transform(prediction)[0]
    st.success(f"Predicted Disease: {disease}")

