# -*- coding: utf-8 -*-
"""practice_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9q_fe2iBjv1laCDdAkUPIsEqbeh5tGm
"""

#!pip install streamlit
import streamlit as st
import pickle
import numpy as np

def load_model():
with open('model.pkl', 'rb') as f:
    pickle.dump(model, f)
model = load_model()

st.title("Student placement predictor")
st.write("Kindly provide your details")
Student_ID = st.number_input("Student_ID", min_value=0.0)
Gender = st.radio("Gender", ["Male", "Female"])
Stream = st.radio("Stream", ["CSE", "ESE", "IT","ME","CE"])
CGPA = st.number_input("CGPA", min_value=0.0)
Tenth_percentage = st.number_input("10th_percentage", min_value=0.0)
Twelveth_percentage = st.number_input("12th_percentage", min_value=0.0)
Backlog = st.radio("Backlog", ["No", "Yes"])
Study_hours_per_day = st.number_input("Study_hours_per_day", min_value=0.0)
attendance_percentage = st.number_input("attendance_percentage", min_value=0.0)
projects_completed	= st.number_input("projects_completed", min_value=0.0)
internships_completed = st.number_input("internships_completed", min_value=0.0)
coding_skills_rating = st.number_input("coding_skills_score", min_value=0.0)

x = np.array([[Student_ID,Gender,Stream,CGPA,Tenth_percentage,Twelveth_percentage,
               Backlog,Study_hours_per_day,attendance_percentage,projects_completed,internships_completed,coding_skills_rating]])

if st.button("Predict"):
    preds = model.predict(x)  # if multi-output, shape = (1, 2)
    y1, y2 = preds[0]
    st.subheader("Predictions")
    st.write(f"Placement_status: {y1}")
    st.write(f"Salary_lpa: {y2}")

