# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NP19aiEnXRvG5rZXpdtZEHXnuKfkCtsc
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

df = pd.read_csv("indian_engineering_student_placement.csv")

df1 = pd.read_csv("placement_targets.csv")

df1 = df1.drop("Student_ID",axis=1)

data = pd.concat([df, df1], axis=1)

data

data.info()

data = data.drop(['communication_skill_rating','aptitude_skill_rating','hackathons_participated','certifications_count','sleep_hours',
                  'stress_level','part_time_job','family_income_level','city_tier','internet_access','extracurricular_involvement'],axis=1)

data

data['branch'].value_counts()

x = data.drop(['placement_status',"salary_lpa"],axis = 1)
y = data[['placement_status',"salary_lpa"]]

# gender encoding
le = LabelEncoder()
x['gender'] = le.fit_transform(x['gender'])

# encode branch
x['branch'] = le.fit_transform(x['branch'])

y = le.fit_transform(y['placement_status'])

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(n_estimators=100, random_state=42)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
mse

import pickle
pickle.dump(model, open("model.pkl", "wb"))

