# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkwysxhTRA_N_m0aAGynpi6fQ4WoLzey
"""

import kagglehub
path = kagglehub.dataset_download("rmisra/news-category-dataset")

import os

for root, dirs, files in os.walk(path):
    for file in files:
        print(os.path.join(root, file))

import pandas as pd

json_file = "/kaggle/input/news-category-dataset/News_Category_Dataset_v3.json"

df = pd.read_json(json_file, lines=True)

print(df.shape)
df.head()

df["category"].value_counts()

required_categories = [
    "TECH",
    "BUSINESS",
    "POLITICS",
    "ENTERTAINMENT"
]

df = df[df["category"].isin(required_categories)]

print(df.shape)
print(df["category"].value_counts())

!pip install -q spacy
!python -m spacy download en_core_web_sm

import spacy

nlp = spacy.load(
    "en_core_web_sm",
    disable=["parser", "ner"]
)

def preprocess(text):

    doc = nlp(text.lower())

    tokens = [
        token.lemma_
        for token in doc
        if not token.is_stop
        and not token.is_punct
    ]

    return " ".join(tokens)

df["clean_headline"] = df["headline"].apply(preprocess)

df[["headline", "clean_headline"]].head()

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(
    ngram_range=(1, 2),
    max_features=5000
)

X = vectorizer.fit_transform(df["clean_headline"])

y = df["category"]

print(X.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000
)

model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

import joblib

joblib.dump(model, "news_model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

def predict_category(headline):

    cleaned = preprocess(headline)

    vector = vectorizer.transform([cleaned])

    prediction = model.predict(vector)

    return prediction[0]

predict_category(
    "Apple unveils its latest AI laptop"
)

print("NewsBot Started")
print("Type 'quit' to exit")

while True:

    headline = input("\nEnter headline: ")

    if headline.lower() in ["quit", "exit"]:
        print("Goodbye!")
        break

    print(
        "Predicted Category:",
        predict_category(headline)
    )

