# -*- coding: utf-8 -*-
"""nlp_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1runFuzYtV7psLIilkxcKSzCBy7JfxSvF
"""

# !pip install streamlit


import streamlit as st
import joblib
import spacy

# -------------------------
# Page Configuration
# -------------------------
st.set_page_config(
    page_title="NewsBot",
    page_icon="📰",
    layout="centered"
)

# -------------------------
# Custom Styling
# -------------------------
st.markdown("""
<style>
.main {
    padding-top: 1rem;
}

.title {
    text-align: center;
    font-size: 3rem;
    font-weight: bold;
}

.subtitle {
    text-align: center;
    color: gray;
    margin-bottom: 30px;
}

.prediction-box {
    padding: 20px;
    border-radius: 15px;
    text-align: center;
    font-size: 24px;
    font-weight: bold;
    margin-top: 20px;
}

.footer {
    text-align:center;
    color:gray;
    margin-top:40px;
}
</style>
""", unsafe_allow_html=True)

# -------------------------
# Load Model
# -------------------------
@st.cache_resource
def load_spacy():
    return spacy.load(
        "en_core_web_sm",
        disable=["parser", "ner"]
    )

@st.cache_resource
def load_model():
    model = joblib.load("assessment/NLP/news_model.pkl")
vectorizer = joblib.load("assessment/NLP/vectorizer.pkl")
    return model, vectorizer

nlp = load_spacy()
model, vectorizer = load_model()

# -------------------------
# Preprocessing
# -------------------------
def preprocess(text):

    doc = nlp(text.lower())

    tokens = [
        token.lemma_
        for token in doc
        if not token.is_stop
        and not token.is_punct
        and not token.is_space
    ]

    return " ".join(tokens)

# -------------------------
# Prediction
# -------------------------
def predict_category(headline):

    cleaned = preprocess(headline)

    vector = vectorizer.transform([cleaned])

    prediction = model.predict(vector)

    return prediction[0]

# -------------------------
# UI
# -------------------------
st.markdown(
    '<div class="title"> NewsBot</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">AI Powered News Headline Classifier</div>',
    unsafe_allow_html=True
)

headline = st.text_area(
    "Enter a News Headline",
    placeholder="Example: Apple unveils its latest AI-powered smartphone...",
    height=120
)

col1, col2 = st.columns([1,1])

with col1:
    predict_btn = st.button(
        "🔍 Predict Category",
        use_container_width=True
    )

with col2:
    clear_btn = st.button(
        "🗑 Clear",
        use_container_width=True
    )

if predict_btn:

    if headline.strip() == "":
        st.warning("Please enter a headline.")
    else:

        category = predict_category(headline)

        color_map = {
            "TECH": "#3498db",
            "BUSINESS": "#2ecc71",
            "POLITICS": "#e74c3c",
            "ENTERTAINMENT": "#9b59b6"
        }

        emoji_map = {
            "TECH": "💻",
            "BUSINESS": "💰",
            "POLITICS": "🏛️",
            "ENTERTAINMENT": "🎬"
        }

        color = color_map.get(category, "#34495e")
        emoji = emoji_map.get(category, "📰")

        st.markdown(
            f"""
            <div class="prediction-box"
                 style="background-color:{color}20;
                        border:2px solid {color};
                        color:{color};">
                {emoji}<br>
                Predicted Category<br><br>
                {category}
            </div>
            """,
            unsafe_allow_html=True
        )

st.markdown("---")

st.subheader("📌 Supported Categories")

c1, c2, c3, c4 = st.columns(4)

with c1:
    st.info("💻 TECH")

with c2:
    st.success("💰 BUSINESS")

with c3:
    st.error("🏛️ POLITICS")

with c4:
    st.warning("🎬 ENTERTAINMENT")

st.markdown(
    """
    <div class="footer">
        Developed using NLP, spaCy, CountVectorizer and Logistic Regression
    </div>
    """,
    unsafe_allow_html=True
)

